platform :ios, '9.0'
use_frameworks!

target 'Example' do
  react_native_path = '../node_modules/react-native'
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  pod 'yoga', path: react_native_path + '/ReactCommon/yoga/yoga.podspec'
  pod 'React', path: react_native_path, subspecs: [
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTBlob',
      'RCTImage',
      'RCTText',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTImage',
      'RCTWebSocket',
  ]

  pod 'cobrowse-sdk-react-native', :path => '../node_modules/cobrowse-sdk-react-native'

end

# cocoapods is super hacky when it comes to swift versions
# https://github.com/CocoaPods/CocoaPods/issues/7134
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
