name: Update native SDKs and create a pull request if necessary

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Find the latest Android SDK version and update build.gradle file
        run: |
          COBROWSE_VERSION=$(wget -O - -o /dev/null https://raw.githubusercontent.com/cobrowseio/cobrowse-sdk-android-binary/master/io/cobrowse/cobrowse-sdk-android/maven-metadata.xml | grep -Eo '<version>[0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?</version>' | grep -Eo '([0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?)' | sort --version-sort -r | head -n 1)
          sed -i '.bak' "s/\(io\.cobrowse\:cobrowse-sdk-android\:\).*/\\1${COBROWSE_VERSION}'/" android/build.gradle
      - name:
        run: |
          COBROWSE_VERSION=$(wget -O - -o /dev/null https://raw.githubusercontent.com/cobrowseio/cobrowse-sdk-ios-binary/master/CobrowseIO.podspec | grep -Eo "s\.version\ +=\ +'[0-9]+\.[0-9]+\.[0-9]+'" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          sed -i '.bak' "s/\(s\.dependency\ *'CobrowseIO\/XCFramework'\,\ *'\).*/\\1${COBROWSE_VERSION}'/" cobrowse-sdk-react-native.podspec
      # If the SDKs were updated, commit the changes and open a new pull request
      - name: Create a new pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES_TO_COMMIT: android/build.gradle cobrowse-sdk-react-native.podspec
          NEW_BRANCH_NAME: feature/update_packages_${{ github.run_id }}
        run: |
          if [[ `git status --porcelain $FILES_TO_COMMIT` ]]; then
            git config --local user.name "Cobrowse.io Bot"
            git config --local user.email "github@cobrowse.io"
            git checkout -b $NEW_BRANCH_NAME
            git add $FILES_TO_COMMIT
            git commit -m "feat: update Cobrowse.io SDK"
            git push origin $NEW_BRANCH_NAME
            gh pr create -B master -H $NEW_BRANCH_NAME --title 'Update native Cobrowse.io SDKs' --body ''
          else
            echo "No changes to commit"
          fi
