name: Update native SDKs and create a pull request if necessary

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'SDK platform (Android or iOS)'
        default: ''
        type: string
        required: true
      cobrowse_sdk_version:
        description: 'Native SDK version'
        default: ''
        type: string
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  android:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.platform == 'Android' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the new Android version from the input parameter
        if: "${{ github.event.inputs.cobrowse_sdk_version != '' }}"
        run: echo "COBROWSE_VERSION=${{ inputs.cobrowse_sdk_version }}" >> $GITHUB_ENV

      - name: Find the new Android version if it is not set
        if: "${{ github.event.cobrowse_sdk_version.level == '' }}"
        run: |
          COBROWSE_VERSION=$(wget -O - -o /dev/null https://raw.githubusercontent.com/cobrowseio/cobrowse-sdk-android-binary/master/io/cobrowse/cobrowse-sdk-android/maven-metadata.xml | grep -Po '(?<=<version>)([0-9\.]+(-SNAPSHOT)?)' | sort --version-sort -r| head -n 1)
          echo "COBROWSE_VERSION=${COBROWSE_VERSION}" >> $GITHUB_ENV

      - name: Update build.gradle file
        run: sed -i "s/\(io\.cobrowse\:cobrowse-sdk-android\:\).*/\\1${COBROWSE_VERSION}'/" sample/build.gradle

      # If the SDK was updated, commit the changes and open a new pull request
      - name: Create a new pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES_TO_COMMIT: android/build.gradle
          NEW_BRANCH_NAME: feature/update_packages_${{ github.run_id }}
        run: |
          if [[ `git status --porcelain $FILES_TO_COMMIT` ]]; then
            git config --local user.name "Cobrowse.io Bot"
            git config --local user.email "github@cobrowse.io"
            git checkout -b $NEW_BRANCH_NAME
            git add $FILES_TO_COMMIT
            git commit -m "feat: update Cobrowse.io SDK"
            git push origin $NEW_BRANCH_NAME
            gh pr create -B master -H $NEW_BRANCH_NAME --title 'Update native Android SDK' --body ''
          else
            echo "No changes to commit"
          fi

  ios:
    runs-on: macos-14
    if: ${{ github.event.inputs.platform == 'iOS' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the new iOS version from the input parameter
        if: "${{ github.event.inputs.cobrowse_sdk_version != '' }}"
        run: echo "COBROWSE_VERSION=${{ inputs.cobrowse_sdk_version }}" >> $GITHUB_ENV

      - name: Find the new iOS version if it is not set
        if: "${{ github.event.cobrowse_sdk_version.level == '' }}"
        run: |
          COBROWSE_VERSION=$(wget -O - -o /dev/null https://raw.githubusercontent.com/cobrowseio/cobrowse-sdk-ios-binary/master/CobrowseIO.podspec | grep -Eo "s\.version\ +=\ +'[0-9]+\.[0-9]+\.[0-9]+'" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          echo "COBROWSE_VERSION=${COBROWSE_VERSION}" >> $GITHUB_ENV

      - name: Update build.gradle file
        run: sed -i "s/\(io\.cobrowse\:cobrowse-sdk-android\:\).*/\\1${COBROWSE_VERSION}'/" sample/build.gradle

      - name: Update Podspec file
        run: sed -i '.bak' "s/\(s\.dependency\ *'CobrowseIO\/XCFramework'\,\ *'\).*/\\1${COBROWSE_VERSION}'/" cobrowse-sdk-react-native.podspec

      # If the SDK was updated, commit the changes and open a new pull request
      - name: Create a new pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES_TO_COMMIT: cobrowse-sdk-react-native.podspec
          NEW_BRANCH_NAME: feature/update_packages_${{ github.run_id }}
        run: |
          if [[ `git status --porcelain $FILES_TO_COMMIT` ]]; then
            git config --local user.name "Cobrowse.io Bot"
            git config --local user.email "github@cobrowse.io"
            git checkout -b $NEW_BRANCH_NAME
            git add $FILES_TO_COMMIT
            git commit -m "feat: update Cobrowse.io SDK"
            git push origin $NEW_BRANCH_NAME
            gh pr create -B master -H $NEW_BRANCH_NAME --title 'Update native iOS SDKs' --body ''
          else
            echo "No changes to commit"
          fi
